### ISSUE TITLE
le fichier 00 instaler2.8

### ISSUE THREAD

**Issue by gmadec56** [d-havard/AppliFrais_Dewi_Hugo_Beno-t_Ga-l#13]
le fichier 00 instaler2.8 est casser je crois enfin peut etre pas mais on sais jamais (c'est quoi deja se fichier)

**Comment by d-havard** [comment]
bah c'est pas à nous de s'en occuper

**Comment by gmadec56** [comment]
ah

**Comment by d-havard** [comment]
bah oui mais relance pas toi

**Comment by d-havard** [comment]
jte jure
