### ISSUE TITLE
changement de base de donnée pour la 1.2

### ISSUE THREAD

**Issue by BenoitC0** [d-havard/AppliFrais_Dewi_Hugo_Beno-t_Ga-l#9]
Le code 1.2 doit ce connecter a la base de donnée "gsbfrais-beta" et non "gsbfrais"

**Comment by BenoitC0** [comment]
rectification ne pas mètre de "-" dans le nom de la base juste "gsbfraisbeta"

**Comment by d-havard** [comment]
Précise mieux depuis le début, c'est mieux ! Sinon dans les fichiers config.php, gsbfrais_bduser et gsbfrais_structure, la modification des bdd peuvent être fait.
